# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'


target 'National_Park' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for National_Park
	pod 'Firebase/Auth'
	pod 'Firebase/Firestore'
  pod 'Kingfisher', '~> 5.15'

end
